In [1]:
import pandas as pd
import numpy as np
import datetime

In [8]:
todays_date = datetime.datetime.now().date()
index = pd.date_range(todays_date, periods=10, freq='D')
cols = ['Sensor_1','Sensor_2','Sensor_3']
df = pd.DataFrame(np.random.randint(5, size=(10, 3)), index=index, columns=cols) 
df

            Sensor_1  Sensor_2  Sensor_3
2020-08-09         1         1         1
2020-08-10         1         1         2
2020-08-11         4         3         0
2020-08-12         3         0         2
2020-08-13         1         2         4
2020-08-14         1         4         4
2020-08-15         4         4         0
2020-08-16         4         1         0
2020-08-17         2         4         3
2020-08-18         2         2         2

In [9]:
for col in cols:
    df[col+'_t-1'] = df[col].shift(1)
    df[col+'_t-2'] = df[col].shift(2)
    df[col+'_t+5'] = df[col].shift(-5)
    df[col+'targ'] = df[col].shift(-5) > df[col]
    df[col+'_avg3'] = df[col].rolling(3).mean()
    df[col+'_std3'] = df[col].rolling(3).std()
df

,Sensor_1,Sensor_2,Sensor_3,Sensor_1_t-1,Sensor_1_t-2,Sensor_1_t+5,Sensor_1targ,Sensor_1_avg3,Sensor_1_std3,Sensor_2_t-1,...,Sensor_2_t+5,Sensor_2targ,Sensor_2_avg3,Sensor_2_std3,Sensor_3_t-1,Sensor_3_t-2,Sensor_3_t+5,Sensor_3targ,Sensor_3_avg3,Sensor_3_std3
2020-08-09,1,1,1,NaN,NaN,1.0,False,NaN,NaN,NaN,...,4.0,True,NaN,NaN,NaN,NaN,4.0,True,NaN,NaN
2020-08-10,1,1,2,1.0,NaN,4.0,True,NaN,NaN,1.0,...,4.0,True,NaN,NaN,1.0,NaN,0.0,False,NaN,NaN
2020-08-11,4,3,0,1.0,1.0,4.0,False,2.000000,1.732051,1.0,...,1.0,False,1.666667,1.154701,2.0,1.0,0.0,False,1.000000,1.000000
2020-08-12,3,0,2,4.0,1.0,2.0,False,2.666667,1.527525,3.0,...,4.0,True,1.333333,1.527525,0.0,2.0,3.0,True,1.333333,1.154701
2020-08-13,1,2,4,3.0,4.0,2.0,True,2.666667,1.527525,0.0,...,2.0,False,1.666667,1.527525,2.0,0.0,2.0,False,2.000000,2.000000
2020-08-14,1,4,4,1.0,3.0,NaN,False,1.666667,1.154701,2.0,...,NaN,False,2.000000,2.000000,4.0,2.0,NaN,False,3.333333,1.154701
2020-08-15,4,4,0,1.0,1.0,NaN,False,2.000000,1.732051,4.0,...,NaN,False,3.333333,1.154701,4.0,4.0,NaN,False,2.666667,2.309401
2020-08-16,4,1,0,4.0,1.0,NaN,False,3.000000,1.732051,4.0,...,NaN,False,3.000000,1.732051,0.0,4.0,NaN,False,1.333333,2.309401
2020-08-17,2,4,3,4.0,4.0,NaN,False,3.333333,1.154701,1.0,...,NaN,False,3.000000,1.732051,0.0,0.0,NaN,False,1.000000,1.732051
2020-08-18,2,2,2,2.0,4.0,NaN,False,2.666667,1.154701,4.0,...,NaN,False,2.333333,1.527525,3.0,0.0,NaN,False,1.666667,1.527525